version: '3.8'

services:
  content-writer:
    build: .
    container_name: content-writer-app
    restart: unless-stopped
    
    # Variables d'environnement
    environment:
      - BASE_PATH=/content-writer
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
    
    # Mapping des ports (interne seulement)
    expose:
      - "8000"
    
    # Volumes pour la persistance (optionnel)
    volumes:
      - ./logs:/app/logs
    
    # Réseau personnalisé
    networks:
      - content-writer-network
    
    # Ressources limitées pour optimiser le VPS
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/content-writer/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logs configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Reverse proxy Nginx (optionnel)
  nginx:
    image: nginx:alpine
    container_name: content-writer-nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    
    depends_on:
      - content-writer
    
    networks:
      - content-writer-network

networks:
  content-writer-network:
    driver: bridge

volumes:
  logs:
    driver: local 